package view;

/**
 *
 * @author singh
 */

import model.User;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import model.Employee;
import service.IAuthenticationService;
import service.AuthenticationService;


public class LoginScreen1 extends javax.swing.JFrame {
    private final IAuthenticationService authService;
    private boolean loginInProgress = false;
    private static final long OTP_EXPIRY_MS = 5 * 60 * 1000;
    
    //Creates new form LoginScreen1
    public LoginScreen1() {
        this(new AuthenticationService());
    }
    
    //Constructor with dependency injection
    public LoginScreen1(IAuthenticationService authService) {
        this.authService = authService;
        initComponents();
        jTextFieldUsername.addActionListener(e -> jButtonLogin.doClick());
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textLogo = new javax.swing.JLabel();
        loginLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelLogin2 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 49, 113));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textLogo.setFont(new java.awt.Font("Kinetika Bold", 0, 55)); // NOI18N
        textLogo.setForeground(new java.awt.Color(255, 255, 255));
        textLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLogo.setText("MotorPH");
        jPanel1.add(textLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 492, -1, -1));

        loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/loginLogo.png"))); // NOI18N
        jPanel1.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 137, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 602));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 282, 201, -1));

        jLabelUsername.setText("Username:");
        jPanel2.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 285, 100, -1));

        jLabelPassword.setText("Password:");
        jPanel2.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 327, 100, -1));

        jButtonLogin.setBackground(new java.awt.Color(14, 49, 113));
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, 32));

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 324, 201, -1));

        jLabelLogin2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelLogin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin2.setText("Employee Login");
        jPanel2.add(jLabelLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 148, -1, -1));

        jButtonReset.setBackground(new java.awt.Color(14, 49, 113));
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Reset Password");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 120, 32));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("CP2 H1102 SY24-25 Team Petix - C.Oreta, S.Singh, R.Sisles, J.Singh, D.Sumatra");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 300, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 0, 590, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        if (loginInProgress) {
            return;
        }
        loginInProgress = true;
        jButtonLogin.setEnabled(false);

        try {
            String username = getEnteredUsername();
            String password = getEnteredPassword();

            if (isLoginBlocked(username)) {
                return;
            }

            Employee emp = authService.authenticate(username, password);
            if (emp == null) {
                showFailedLogin(username);
                clearLoginInputs();
                return;
            }

            if (performTwoFactorChallenge()) {
                proceedWithSuccessfulLogin(emp, username);
            }
        } finally {
            loginInProgress = false;
            jButtonLogin.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        jButtonLogin.doClick();
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        String empId = JOptionPane.showInputDialog(this, "Enter your Employee ID:");
        if (empId == null || empId.trim().isEmpty()) return;

        // Get security question using service
        String question = authService.getSecurityQuestion(empId.trim());
        if (question == null) {
            JOptionPane.showMessageDialog(this, "Employee ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String answer = JOptionPane.showInputDialog(this, question);
        if (answer == null || answer.trim().isEmpty()) return;

        // Verify security answer using service
        boolean isCorrect = authService.verifySecurityAnswer(empId.trim(), answer.trim());
        if (!isCorrect) {
            JOptionPane.showMessageDialog(this, "Incorrect answer. Please try again.", "Security Check Failed", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String newPassword = promptForValidPassword();
        if (newPassword == null) {
            return;
        }

        // Update password using service
        boolean updated = authService.updatePassword(empId.trim(), newPassword);
        if (updated) {
            JOptionPane.showMessageDialog(this, "Password reset successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update password.", "Update Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    // --- NEW HELPER METHODS ---

     //Encapsulates the actions for a successful login, whether 2FA was used or not.
     //This method will open the MainMenu and dispose of the LoginScreen.
     //@param user The authenticated User object.
    private void proceedWithSuccessfulLogin(Employee emp, String username) {
        // Reset failed login attempts in service
        authService.clearFailedLoginAttempts(username);
        model.User.setLoggedInUser(emp);
        showWelcomePopup(emp);

        // POLYMORPHISM: Pass the Employee object to the MainMenu
        // This allows MainMenu to handle permissions based on the object type
        MainMenu main = new MainMenu(emp); 
        main.setVisible(true);
        main.setLocationRelativeTo(null);

        this.dispose(); // Close the current login screen
    }

    private void showWelcomePopup(Employee emp) {
        String firstName = (emp == null || emp.getFirstName() == null)
                ? ""
                : emp.getFirstName().trim();
        if (firstName.isEmpty()) {
            firstName = "User";
        }
        JOptionPane.showMessageDialog(
                this,
                "Welcome " + firstName,
                "Welcome",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private String getEnteredUsername() {
        return jTextFieldUsername.getText().trim();
    }

    private String getEnteredPassword() {
        return new String(jPasswordField.getPassword()).trim();
    }

    private void clearLoginInputs() {
        jTextFieldUsername.setText("");
        jPasswordField.setText("");
    }

    private boolean isLoginBlocked(String username) {
        if (!authService.isAccountLocked(username)) {
            return false;
        }
        long secondsRemaining = (authService.getAccountUnlockTime(username) - System.currentTimeMillis()) / 1000;
        JOptionPane.showMessageDialog(this,
                "Your account is temporarily locked.\nPlease try again in " + secondsRemaining + " seconds.",
                "Account Locked",
                JOptionPane.WARNING_MESSAGE);
        return true;
    }

    private void showFailedLogin(String username) {
        String errorMsg = authService.getLastError();
        if (authService.getFailedLoginAttempts(username) >= 3) {
            JOptionPane.showMessageDialog(this,
                    "Invalid login 3 times.\nAccount is locked for 5 minutes.\n" +
                            "Consider resetting your password.",
                    "Account Temporarily Blocked",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this,
                errorMsg != null ? errorMsg : "Invalid username or password.",
                "Login Failed",
                JOptionPane.WARNING_MESSAGE);
    }

    private boolean performTwoFactorChallenge() {
        String otp = authService.generateOtp();
        long otpIssuedAt = System.currentTimeMillis();
        boolean sent = authService.sendOtpEmail(null, otp);
        if (!sent) {
            String reason = authService.getLastError();
            JOptionPane.showMessageDialog(
                    this,
                    "Failed to send verification code.\n"
                            + (reason == null || reason.isBlank() ? "Please try again." : reason),
                    "2FA Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        JOptionPane.showMessageDialog(
                this,
                "Demo verification code: " + otp + "\nEnter this 6-digit code in the next prompt.",
                "Two-Factor Authentication",
                JOptionPane.INFORMATION_MESSAGE);

        String enteredOTP = JOptionPane.showInputDialog(this, "Enter the 6-digit verification code:");
        if (enteredOTP == null || enteredOTP.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "OTP not entered. Login failed.", "2FA Canceled", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (System.currentTimeMillis() - otpIssuedAt > OTP_EXPIRY_MS) {
            JOptionPane.showMessageDialog(this, "OTP expired. Please log in again.", "2FA Expired", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!otp.equals(enteredOTP.trim())) {
            JOptionPane.showMessageDialog(this, "Invalid OTP. Login failed.", "2FA Failed", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private String promptForValidPassword() {
        while (true) {
            JPasswordField passwordField = new JPasswordField();
            passwordField.setEchoChar('*');
            int confirm = JOptionPane.showConfirmDialog(this, passwordField, "Enter your new password:", JOptionPane.OK_CANCEL_OPTION);
            if (confirm != JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(this, "Password reset canceled.");
                return null;
            }

            String newPassword = new String(passwordField.getPassword()).trim();
            if (authService.validatePasswordFormat(newPassword)) {
                return newPassword;
            }

            JOptionPane.showMessageDialog(this,
                    "Password must meet the following requirements:\n" +
                            "- Only letters and numbers (no symbols)\n" +
                            "- At least one uppercase letter\n" +
                            "- At least one number",
                    "Invalid Password Format",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogin2;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JLabel textLogo;
    // End of variables declaration//GEN-END:variables
}
