//The MainMenu class represents the main dashboard after successful login.

package view;

import model.*;
import repository.*;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;


import view.Attendance;
import view.LoginScreen1;
import model.User;
import model.Employee;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import model.AdminStaff;
import model.FinanceStaff;
import model.HRStaff;
import model.ITStaff;
import model.RegularEmployee;
import repository.AttendanceRepository;
import view.EditEmpInfo;
import view.EmployeeTable;
import view.Payslip;


public class MainMenu extends javax.swing.JFrame {

    // OOP: Using the Parent class Employee for Polymorphism
    private Employee currentUser;

    // GUI modules
    private EmployeeTable femptable;
    private Payslip fpayslip;
    private Attendance fattendance;

    //Default constructor (optional for testing or fallback)

    public MainMenu() {
        initComponents();
        initModules();
    }

    //Constructor with user info passed from Login

    public MainMenu(Employee employee) {
        this.currentUser = employee;
        initComponents();
        initModules();
        
        if (employee != null && jLabelWelcome != null) {
            jLabelWelcome.setText("Welcome, " + employee.getFirstName() + " " + employee.getLastName());
            applyRolePermissions();
        }
    }
        private void applyRolePermissions() {
        // Example: Only IT and Admin can see certain system buttons
        // This is where you'd hide buttons for RegularEmployees
        if (currentUser instanceof RegularEmployee) {
            // Regular employees might not need the Employee Information table access
            // jButtonEmployee.setVisible(false); 
            // jButtonSettings.setVisible (false);
        }
    }

    // Initializes form modules
    private void initModules() {
        femptable = new EmployeeTable();
        fpayslip = new Payslip();
        fattendance = new Attendance();
    }
    
    private void openAttendanceForSupervisedEmployee() {
    String supervisorName = User.getLoggedInUser().getLastName().trim() + "  " + User.getLoggedInUser().getFirstName().trim();
    List<Employee> supervised = new ArrayList<>();

    for (Employee emp : new repository.EmployeeRepository().findAll()) {
        if (emp.getSupervisor().trim().equalsIgnoreCase(supervisorName)) {
            supervised.add(emp);
        }
    }

    if (supervised.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No supervised employees found.", "Info", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    String[] namesWithIDs = supervised.stream()
        .map(e -> e.getFirstName() + " " + e.getLastName() + " (" + e.getEmployeeNumber() + ")")
        .toArray(String[]::new);

    String selection = (String) JOptionPane.showInputDialog(
        this,
        "Select an employee:",
        "Attendance Viewer",
        JOptionPane.PLAIN_MESSAGE,
        null,
        namesWithIDs,
        namesWithIDs[0]
    );

    if (selection != null && !selection.trim().isEmpty()) {
        String empId = selection.replaceAll(".*\\((\\d+)\\).*", "$1"); // Extract numeric ID
        new Attendance(empId).setVisible(true);
    }
}

    
    // In EditEmpInfo.java

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jButtonTimein = new javax.swing.JButton();
        jButtonTimeout = new javax.swing.JButton();
        headerLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEmployee = new javax.swing.JButton();
        jButtonPayslip = new javax.swing.JButton();
        jButtonAttendance = new javax.swing.JButton();
        jButtonExit2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setFont(new java.awt.Font("Kinetika Bold", 1, 36)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setText("Welcome, Manuel Garcia III");
        jLabelWelcome.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jButtonTimein.setBackground(new java.awt.Color(0, 51, 204));
        jButtonTimein.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTimein.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimein.setText("Time IN");
        jButtonTimein.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTimein.setPreferredSize(new java.awt.Dimension(83, 25));
        jButtonTimein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimeinActionPerformed(evt);
            }
        });

        jButtonTimeout.setBackground(new java.awt.Color(0, 51, 204));
        jButtonTimeout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTimeout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimeout.setText("Time OUT");
        jButtonTimeout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTimeout.setPreferredSize(new java.awt.Dimension(80, 25));
        jButtonTimeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimeoutActionPerformed(evt);
            }
        });

        headerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/logoHeader.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelWelcome)
                .addGap(240, 240, 240)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(headerLogo))
                    .addComponent(jButtonTimein, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButtonTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerLogo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTimein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWelcome)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));

        jButtonEmployee.setBackground(new java.awt.Color(14, 49, 113));
        jButtonEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmployee.setText("Employee Information");
        jButtonEmployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeActionPerformed(evt);
            }
        });

        jButtonPayslip.setBackground(new java.awt.Color(14, 49, 113));
        jButtonPayslip.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPayslip.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPayslip.setText("Payslip");
        jButtonPayslip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayslipActionPerformed(evt);
            }
        });

        jButtonAttendance.setBackground(new java.awt.Color(14, 49, 113));
        jButtonAttendance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAttendance.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAttendance.setText("Attendance");
        jButtonAttendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendanceActionPerformed(evt);
            }
        });

        jButtonExit2.setBackground(new java.awt.Color(153, 0, 0));
        jButtonExit2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit2.setText("Sign Out");
        jButtonExit2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("CP2 H1102 SY24-25 Team Petix - C.Oreta, S.Singh, R.Sisles, J.Singh, D.Sumatra");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jButtonPayslip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(869, 869, 869)
                        .addComponent(jButtonExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButtonPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButtonAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTimeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimeinActionPerformed
        if (currentUser != null) {
            AttendanceRepository attendanceRepo = new AttendanceRepository();
            String today = java.time.LocalDate.now().format(java.time.format.DateTimeFormatter.ofPattern("MM/dd/yyyy"));
            String now = java.time.LocalTime.now().format(java.time.format.DateTimeFormatter.ofPattern("H:mm"));
            
            if (attendanceRepo.hasLoggedToday(String.valueOf(currentUser.getEmployeeNumber()), today)){
                 JOptionPane.showMessageDialog(this, "Already clocked in today.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                 model.AttendanceRecord record = new model.AttendanceRecord (
                        String.valueOf(currentUser.getEmployeeNumber()),
                        currentUser.getLastName(),
                        currentUser.getFirstName(),
                        today, now, ""
                 );
                 attendanceRepo.save(record);
                 JOptionPane.showMessageDialog(this, "Time In recorded at " + now);
            }
        }
    }//GEN-LAST:event_jButtonTimeinActionPerformed

    private void jButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeActionPerformed
                                    
    // POLYMORPHISM: Check the class type
        if (currentUser instanceof AdminStaff || currentUser instanceof HRStaff || currentUser instanceof FinanceStaff) {
            // Admins, Finance and HR see the full table
            femptable.setVisible(true);
            femptable.setLocationRelativeTo(null);
            
        } else {
            /// Regular employees or IT see only their own info
            EditEmpInfo editInfo = new EditEmpInfo(currentUser.getEmployeeNumber(), true);
            editInfo.setVisible(true);
            editInfo.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButtonEmployeeActionPerformed

    private void jButtonPayslipActionPerformed(java.awt.event.ActionEvent evt) {
        // Polymorphic check: ADMIN, HR, and FINANCE have special access
        String currentEmpId = String.valueOf(currentUser.getEmployeeNumber());
        
        if (currentUser instanceof AdminStaff || currentUser instanceof HRStaff || currentUser instanceof FinanceStaff) {
            Object[] options = {"View My Own", "View Other Employee"};
            int choice = JOptionPane.showOptionDialog(this, "Select Access Mode", "Payroll",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

            if (choice == JOptionPane.YES_OPTION) {
                new Payslip(currentEmpId).setVisible(true);
            } else if (choice == JOptionPane.NO_OPTION) {
                new EmployeeTable().setVisible(true);
            }
        } else {
            new Payslip(currentEmpId).setVisible(true);
    }
}

    private void jButtonExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit2ActionPerformed
     int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to log out?",
        "Logout Confirmation",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        dispose(); // Close MainMenu
        new LoginScreen1().setVisible(true); // Open LoginScreen1
}
    }//GEN-LAST:event_jButtonExit2ActionPerformed

   private void jButtonTimeoutActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentUser != null) {
        repository.AttendanceRepository attendanceRepo = new repository.AttendanceRepository();
        
        // 1. Get current date and time
        String today = java.time.LocalDate.now().format(java.time.format.DateTimeFormatter.ofPattern("MM/dd/yyyy"));
        String now = java.time.LocalTime.now().format(java.time.format.DateTimeFormatter.ofPattern("H:mm"));
        String empId = String.valueOf(currentUser.getEmployeeNumber());

        // 2. Check if the user has even timed in yet today
        if (!attendanceRepo.hasLoggedToday(empId, today)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No Time In record found for today.",
                    "Missing Log",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            // 3. Create the record object with the logout time
            model.AttendanceRecord record = new model.AttendanceRecord(
                    empId,
                    currentUser.getLastName(),
                    currentUser.getFirstName(),
                    today,
                    "", // We don't need to pass Time In here, the update method handles it
                    now  // This is our LogOut time
            );

            // 4. Update using your repository
            attendanceRepo.update(record);
            javax.swing.JOptionPane.showMessageDialog(this, "Time Out recorded at " + now);
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "User session not found.");
    }
}                   

    private void jButtonAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendanceActionPerformed
        
        if (currentUser instanceof AdminStaff || currentUser instanceof HRStaff || currentUser instanceof FinanceStaff) {
             new EmployeeTable().setVisible(true);
        } else {
             new Attendance(String.valueOf(currentUser.getEmployeeNumber())).setVisible(true);
        }
    }//GEN-LAST:event_jButtonAttendanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLogo;
    private javax.swing.JButton jButtonAttendance;
    private javax.swing.JButton jButtonEmployee;
    private javax.swing.JButton jButtonExit2;
    private javax.swing.JButton jButtonPayslip;
    private javax.swing.JButton jButtonTimein;
    private javax.swing.JButton jButtonTimeout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
