package view;

import repository.EmployeeRepository;
import service.AttendanceService;
import service.SalaryService;
import model.Employee;
import javax.swing.JOptionPane;
import java.io.FileOutputStream;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import javax.swing.JFileChooser;
import model.User;
import repository.AttendanceRepository;
import service.ISalaryService;


/**
 *
 * @author singh
 */


public class Payslip extends javax.swing.JFrame {
        private String empNo;
        private final ISalaryService salaryService = new SalaryService();

    public Payslip(String empNo){
        initComponents();
        this.empNo = empNo;
        
        Employee emp = new EmployeeRepository().findById(Integer.parseInt(empNo)).orElse(null);
            if (emp != null) {
        employeeNameLabel.setText(emp.getLastName() + ", " + emp.getFirstName());
            }
            
        this.setLocationRelativeTo(null);
}
    

    /**
     * Creates new form Payslip
     */
    public Payslip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ElectronicPayslip = new javax.swing.JLabel();
        employeeNameLabel = new javax.swing.JLabel();
        cutOff = new javax.swing.JLabel();
        fromDate = new com.toedter.calendar.JDateChooser();
        cutOff1 = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        viewPayslip = new javax.swing.JButton();
        downloadPayslip = new javax.swing.JButton();
        summary = new javax.swing.JLabel();
        summary1 = new javax.swing.JLabel();
        grossIncomeValue = new javax.swing.JLabel();
        benefits = new javax.swing.JLabel();
        benefitsValue = new javax.swing.JLabel();
        deductions = new javax.swing.JLabel();
        deductionValue = new javax.swing.JLabel();
        deductions1 = new javax.swing.JLabel();
        otherAdjustmentValue = new javax.swing.JLabel();
        netPay = new javax.swing.JLabel();
        netPayValue = new javax.swing.JLabel();
        payDetails = new javax.swing.JLabel();
        salaryDetails = new javax.swing.JLabel();
        empIDPayslip = new javax.swing.JLabel();
        hoursWorked = new javax.swing.JLabel();
        hourlyRate = new javax.swing.JLabel();
        overtime = new javax.swing.JLabel();
        hoursWorkedValue = new javax.swing.JLabel();
        hourlyRateValue = new javax.swing.JLabel();
        overtimeValue = new javax.swing.JLabel();
        allowances = new javax.swing.JLabel();
        hoursWorked1 = new javax.swing.JLabel();
        hoursWorked2 = new javax.swing.JLabel();
        hoursWorked3 = new javax.swing.JLabel();
        deductionsBreakdown = new javax.swing.JLabel();
        pagibigDeductions = new javax.swing.JLabel();
        sssDeductions = new javax.swing.JLabel();
        philhealthDeductions = new javax.swing.JLabel();
        phoneAllowanceValue = new javax.swing.JLabel();
        clothingAllowanceValue = new javax.swing.JLabel();
        riceAllowanceValue = new javax.swing.JLabel();
        sssDeductionsValue = new javax.swing.JLabel();
        philhealthDeductionsValue = new javax.swing.JLabel();
        pagibigDeductionsValue = new javax.swing.JLabel();
        withholdingTaxDeductions = new javax.swing.JLabel();
        withholdingTaxDeductionsValue = new javax.swing.JLabel();
        empPosition = new javax.swing.JLabel();
        empStatus = new javax.swing.JLabel();
        pagibigNumberPayslip = new javax.swing.JLabel();
        sssNumberPayslip = new javax.swing.JLabel();
        philhealthNumberPayslip = new javax.swing.JLabel();
        tinNumberPayslip = new javax.swing.JLabel();
        employeeDetails = new javax.swing.JLabel();
        sssNumberPayslipValue = new javax.swing.JLabel();
        philhealthNumberPayslipValue = new javax.swing.JLabel();
        pagibigNumberPayslipValue = new javax.swing.JLabel();
        tinNumberPayslipValue = new javax.swing.JLabel();
        empIDPayslipValue = new javax.swing.JLabel();
        empPositionValue = new javax.swing.JLabel();
        empStatusValue = new javax.swing.JLabel();
        payDateLabel = new javax.swing.JLabel();
        exitPayslip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ElectronicPayslip.setText("ELECTRONIC PAYSLIP OF:");

        cutOff.setText("Cutoff:");

        cutOff1.setText("to: ");

        viewPayslip.setText("View Payslip");
        viewPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPayslipActionPerformed(evt);
            }
        });

        downloadPayslip.setText("Download ");
        downloadPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadPayslipActionPerformed(evt);
            }
        });

        summary.setText("SUMMARY:");

        summary1.setText("Gross Income:");

        grossIncomeValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        benefits.setText("Benefits:");

        benefitsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        deductions.setText("Deductions:");

        deductionValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        deductions1.setText("Other Adjustments:");

        otherAdjustmentValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        netPay.setText("NET PAY:");

        netPayValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        payDetails.setText("PAY DETAILS:");

        salaryDetails.setText("Salary Details:");

        empIDPayslip.setText("Employee ID:");

        hoursWorked.setText("Hours worked:");

        hourlyRate.setText("Hourly rate:");

        overtime.setText("Overtime:");

        hoursWorkedValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        hourlyRateValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        overtimeValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        allowances.setText("Allownaces:");

        hoursWorked1.setText("Phone:");

        hoursWorked2.setText("Clothing:");

        hoursWorked3.setText("Rice:");

        deductionsBreakdown.setText("Deductions: ");

        pagibigDeductions.setText("Pag IBIG:");

        sssDeductions.setText("SSS Premium:");

        philhealthDeductions.setText("Philhealth:");

        phoneAllowanceValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clothingAllowanceValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        riceAllowanceValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sssDeductionsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        philhealthDeductionsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pagibigDeductionsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        withholdingTaxDeductions.setText("Withholding Tax:");

        withholdingTaxDeductionsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        empPosition.setText("Employee Position: ");

        empStatus.setText("Employee Status:");

        pagibigNumberPayslip.setText("Pag IBIG:");

        sssNumberPayslip.setText("SSS:");

        philhealthNumberPayslip.setText("Philhealth:");

        tinNumberPayslip.setText("TIN:");

        employeeDetails.setText("EMPLOYEE DETAILS:");

        sssNumberPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        philhealthNumberPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pagibigNumberPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tinNumberPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        empIDPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        empPositionValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        empStatusValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        exitPayslip.setText("EXIT");
        exitPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitPayslipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ElectronicPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(netPay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(summary1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(benefits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deductions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deductions1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(benefitsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(grossIncomeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deductionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(otherAdjustmentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(netPayValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(summary, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salaryDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(hourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hourlyRateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(hoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hoursWorkedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(hoursWorked1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hoursWorked2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hoursWorked3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(overtime, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sssDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(philhealthDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pagibigDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(overtimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(clothingAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(phoneAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(riceAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(philhealthDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sssDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pagibigDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(withholdingTaxDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(withholdingTaxDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(allowances, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deductionsBreakdown, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(payDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cutOff, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(cutOff1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(payDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sssNumberPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(philhealthNumberPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pagibigNumberPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tinNumberPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empIDPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sssNumberPayslipValue, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(philhealthNumberPayslipValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pagibigNumberPayslipValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tinNumberPayslipValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(empIDPayslipValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(empPositionValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(empStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(viewPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(downloadPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElectronicPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cutOff)
                    .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cutOff1)
                    .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(payDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewPayslip)
                            .addComponent(downloadPayslip))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summary)
                    .addComponent(payDetails)
                    .addComponent(employeeDetails))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grossIncomeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryDetails)
                    .addComponent(summary1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(benefitsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(benefits))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deductionValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deductions)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hoursWorkedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoursWorked))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(overtime)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hourlyRateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hourlyRate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(overtimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empIDPayslip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empPosition)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empIDPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empPositionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empStatusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherAdjustmentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductions1)
                    .addComponent(allowances))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hoursWorked1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hoursWorked2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hoursWorked3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clothingAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(riceAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deductionsBreakdown))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sssNumberPayslip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(philhealthNumberPayslip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pagibigNumberPayslip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tinNumberPayslip)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(netPayValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(netPay))
                                .addGap(109, 109, 109))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sssDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(philhealthDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pagibigDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sssDeductions)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(philhealthDeductions)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pagibigDeductions)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(withholdingTaxDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(withholdingTaxDeductions))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sssNumberPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(philhealthNumberPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagibigNumberPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tinNumberPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitPayslip)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadPayslipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downloadPayslipActionPerformed

    private void viewPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPayslipActionPerformed
            // TODO add your handling code here:
       java.util.Date start = fromDate.getDate();
    java.util.Date end = toDate.getDate();

    if (start == null || end == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select both dates!");
        return; 
    }

    // 2. Fetch the Employee (The heart of the operation)
    EmployeeRepository empRepo = new EmployeeRepository();
    Employee emp = empRepo.findById(Integer.parseInt(this.empNo)).orElse(null);

    if (emp == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Employee not found!");
        return;
    }

    // 3. Format dates properly to fix the "Jun 1" Parse Error
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MM/dd/yyyy");
    String startStr = sdf.format(start);
    String endStr = sdf.format(end);

    // 4. Determine the Cutoff Label
    java.util.Calendar cal = java.util.Calendar.getInstance();
    cal.setTime(start);
    int day = cal.get(java.util.Calendar.DAY_OF_MONTH);
    
    String periodLabel = (day <= 15) ? "1st - 15th of the Month" : "16th - End of the Month";
    payDateLabel.setText(periodLabel);

    // 5. Get Attendance Hours (Using the formatted strings)
    AttendanceRepository attendanceRepo = new AttendanceRepository();
    double actualHours = attendanceRepo.getTotalHoursInRange(this.empNo, startStr, endStr);
    
    if (actualHours <= 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "No attendance records found for this period. Net Pay is ₱0.00.");
    
    updateSalaryDisplay(emp, 0.0, 0.0); 
    return;
    }
    // 6. UI Update Sequence
    // This fills static info (SSS, TIN, etc.)
    fillEmployeeDetails(emp); 
    
    // This fills the financial boxes (Gross, Net, Deductions)
    updateSalaryDisplay(emp, actualHours, 0.0);
    
    }//GEN-LAST:event_viewPayslipActionPerformed

    private void exitPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPayslipActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitPayslipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payslip().setVisible(true);
            }
        });
    }
    
    private void updateSalaryDisplay(Employee emp, double hours, double ot) {
    // 1. Get the math from service
    double gross = salaryService.calculateGrossIncome(emp, hours, ot);
    double monthlyEquivalent = gross * 2; 

    // 2. SET THE MISSING FIELDS
    // Set the rate first so the user sees what they earn per hour
    hourlyRateValue.setText(String.format("%.2f", emp.getHourlyRate()));
    
    // Set the hours worked and overtime
    hoursWorkedValue.setText(String.format("%.2f", hours));
    overtimeValue.setText(String.format("%.2f", ot));
    
    // Set the Gross Income (Summary and Pay Details)
    grossIncomeValue.setText(String.format("₱%,.2f", gross));
    
    // 3. SET DEDUCTIONS (Using your SalaryService)
    double sss = salaryService.calculateSSS(monthlyEquivalent) / 2;
    double philhealth = salaryService.calculatePhilHealth(monthlyEquivalent) / 2;
    double pagibig = salaryService.calculatePagIbig(monthlyEquivalent) / 2;
   
    
    // Fill the Pag-IBIG and Tax boxes which were ₱0.00 in your screenshot
    pagibigDeductionsValue.setText(String.format("₱%,.2f", pagibig));
    
    double totalDeductions = sss + philhealth + pagibig;
    double taxableIncome = gross - totalDeductions;
    double tax = salaryService.calculateWithholdingTax(taxableIncome);
    
    
    withholdingTaxDeductionsValue.setText(String.format("₱%,.2f", tax));
    deductionValue.setText(String.format("₱%,.2f", totalDeductions + tax));
    
    // 4. FINAL NET PAY
    double netPay = taxableIncome - tax + (emp.getTotalAllowances() / 2);
    netPayValue.setText(String.format("₱%,.2f", netPay));
}
    
    private void fillEmployeeDetails(Employee emp) {
	
    if (emp != null) {
        
    // 1.Employee Identity
    empIDPayslipValue.setText(String.valueOf(emp.getEmployeeNumber()));
    empPositionValue.setText(emp.getPosition());
    empStatusValue.setText(emp.getStatus());

    //2.Statutory IDs
    sssNumberPayslipValue.setText(emp.getSssNumber());
    tinNumberPayslipValue.setText(emp.getTinNumber());
    philhealthNumberPayslipValue.setText(emp.getPhilHealthNumber());
    pagibigNumberPayslipValue.setText(emp.getPagIbigNumber());
    
    // Allowances
    
    
    double semiMonthlyRice = emp.getRiceSubsidy() / 2;
    double semiMonthlyPhone = emp.getPhoneAllowance() / 2;
    double semiMonthlyClothing = emp.getClothingAllowance() / 2;
    
    riceAllowanceValue.setText(String.format("%.2f", emp.getRiceSubsidy()));
    phoneAllowanceValue.setText(String.format("%.2f", emp.getPhoneAllowance()));
    clothingAllowanceValue.setText(String.format("%.2f", emp.getClothingAllowance()));
    
    hourlyRateValue.setText(String.format("%.2f", emp.getHourlyRate()));
}
    }

 private void calculateFinalSalary(String empNo, String period) {
        try {
            payDateLabel.setText(period);
            empIDPayslipValue.setText(empNo);
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElectronicPayslip;
    private javax.swing.JLabel allowances;
    private javax.swing.JLabel benefits;
    private javax.swing.JLabel benefitsValue;
    private javax.swing.JLabel clothingAllowanceValue;
    private javax.swing.JLabel cutOff;
    private javax.swing.JLabel cutOff1;
    private javax.swing.JLabel deductionValue;
    private javax.swing.JLabel deductions;
    private javax.swing.JLabel deductions1;
    private javax.swing.JLabel deductionsBreakdown;
    private javax.swing.JButton downloadPayslip;
    private javax.swing.JLabel empIDPayslip;
    private javax.swing.JLabel empIDPayslipValue;
    private javax.swing.JLabel empPosition;
    private javax.swing.JLabel empPositionValue;
    private javax.swing.JLabel empStatus;
    private javax.swing.JLabel empStatusValue;
    private javax.swing.JLabel employeeDetails;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JButton exitPayslip;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JLabel grossIncomeValue;
    private javax.swing.JLabel hourlyRate;
    private javax.swing.JLabel hourlyRateValue;
    private javax.swing.JLabel hoursWorked;
    private javax.swing.JLabel hoursWorked1;
    private javax.swing.JLabel hoursWorked2;
    private javax.swing.JLabel hoursWorked3;
    private javax.swing.JLabel hoursWorkedValue;
    private javax.swing.JLabel netPay;
    private javax.swing.JLabel netPayValue;
    private javax.swing.JLabel otherAdjustmentValue;
    private javax.swing.JLabel overtime;
    private javax.swing.JLabel overtimeValue;
    private javax.swing.JLabel pagibigDeductions;
    private javax.swing.JLabel pagibigDeductionsValue;
    private javax.swing.JLabel pagibigNumberPayslip;
    private javax.swing.JLabel pagibigNumberPayslipValue;
    private javax.swing.JLabel payDateLabel;
    private javax.swing.JLabel payDetails;
    private javax.swing.JLabel philhealthDeductions;
    private javax.swing.JLabel philhealthDeductionsValue;
    private javax.swing.JLabel philhealthNumberPayslip;
    private javax.swing.JLabel philhealthNumberPayslipValue;
    private javax.swing.JLabel phoneAllowanceValue;
    private javax.swing.JLabel riceAllowanceValue;
    private javax.swing.JLabel salaryDetails;
    private javax.swing.JLabel sssDeductions;
    private javax.swing.JLabel sssDeductionsValue;
    private javax.swing.JLabel sssNumberPayslip;
    private javax.swing.JLabel sssNumberPayslipValue;
    private javax.swing.JLabel summary;
    private javax.swing.JLabel summary1;
    private javax.swing.JLabel tinNumberPayslip;
    private javax.swing.JLabel tinNumberPayslipValue;
    private com.toedter.calendar.JDateChooser toDate;
    private javax.swing.JButton viewPayslip;
    private javax.swing.JLabel withholdingTaxDeductions;
    private javax.swing.JLabel withholdingTaxDeductionsValue;
    // End of variables declaration//GEN-END:variables
}