package view;

import repository.EmployeeRepository;
import service.SalaryService;
import model.Employee;
import model.PayslipData;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import java.io.FileOutputStream;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import model.User;
import service.ISalaryService;


/**
 *
 * @author singh
 */


public class Payslip extends javax.swing.JFrame {
        private String empNo;
        private final ISalaryService salaryService = new SalaryService();
        private static final DateTimeFormatter CSV_DATE_FORMAT = DateTimeFormatter.ofPattern("MM/dd/yyyy");
        private final Map<String, LocalDate> cutoffDateOptions = new LinkedHashMap<>();

    public Payslip(String empNo){
        initComponents();
        setAttendanceAdjustmentVisibility(false, false, false);
        hourlyRate.setVisible(false);
        hourlyRateValue.setVisible(false);
        this.empNo = empNo;
        
        Employee emp = new EmployeeRepository().findById(Integer.parseInt(empNo)).orElse(null);
            if (emp != null) {
        employeeNameLabel.setText(emp.getLastName() + ", " + emp.getFirstName());
            }
            
        loadCutoffDateOptions();
        this.setLocationRelativeTo(null);
}
    

    /**
     * Creates new form Payslip
     */
    public Payslip() {
        initComponents();
        setAttendanceAdjustmentVisibility(false, false, false);
        hourlyRate.setVisible(false);
        hourlyRateValue.setVisible(false);
        cutoffDateCombo.setModel(new DefaultComboBoxModel<>(new String[] {"Select cutoff date"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ElectronicPayslip = new javax.swing.JLabel();
        employeeNameLabel = new javax.swing.JLabel();
        cutOff = new javax.swing.JLabel();
        cutoffDateCombo = new javax.swing.JComboBox<>();
        viewPayslip = new javax.swing.JButton();
        downloadPayslip = new javax.swing.JButton();
        summary = new javax.swing.JLabel();
        summary1 = new javax.swing.JLabel();
        grossIncomeValue = new javax.swing.JLabel();
        benefits = new javax.swing.JLabel();
        benefitsValue = new javax.swing.JLabel();
        deductions = new javax.swing.JLabel();
        deductionValue = new javax.swing.JLabel();
        deductions1 = new javax.swing.JLabel();
        otherAdjustmentValue = new javax.swing.JLabel();
        netPay = new javax.swing.JLabel();
        netPayValue = new javax.swing.JLabel();
        payDetails = new javax.swing.JLabel();
        salaryDetails = new javax.swing.JLabel();
        empIDPayslip = new javax.swing.JLabel();
        hoursWorked = new javax.swing.JLabel();
        hourlyRate = new javax.swing.JLabel();
        overtime = new javax.swing.JLabel();
        lateLabel = new javax.swing.JLabel();
        undertimeLabel = new javax.swing.JLabel();
        hoursWorkedValue = new javax.swing.JLabel();
        hourlyRateValue = new javax.swing.JLabel();
        overtimeValue = new javax.swing.JLabel();
        lateValue = new javax.swing.JLabel();
        undertimeValue = new javax.swing.JLabel();
        allowances = new javax.swing.JLabel();
        hoursWorked1 = new javax.swing.JLabel();
        hoursWorked2 = new javax.swing.JLabel();
        hoursWorked3 = new javax.swing.JLabel();
        deductionsBreakdown = new javax.swing.JLabel();
        pagibigDeductions = new javax.swing.JLabel();
        sssDeductions = new javax.swing.JLabel();
        philhealthDeductions = new javax.swing.JLabel();
        phoneAllowanceValue = new javax.swing.JLabel();
        clothingAllowanceValue = new javax.swing.JLabel();
        riceAllowanceValue = new javax.swing.JLabel();
        sssDeductionsValue = new javax.swing.JLabel();
        philhealthDeductionsValue = new javax.swing.JLabel();
        pagibigDeductionsValue = new javax.swing.JLabel();
        withholdingTaxDeductions = new javax.swing.JLabel();
        withholdingTaxDeductionsValue = new javax.swing.JLabel();
        empPosition = new javax.swing.JLabel();
        empStatus = new javax.swing.JLabel();
        pagibigNumberPayslip = new javax.swing.JLabel();
        sssNumberPayslip = new javax.swing.JLabel();
        philhealthNumberPayslip = new javax.swing.JLabel();
        tinNumberPayslip = new javax.swing.JLabel();
        employeeDetails = new javax.swing.JLabel();
        sssNumberPayslipValue = new javax.swing.JLabel();
        philhealthNumberPayslipValue = new javax.swing.JLabel();
        pagibigNumberPayslipValue = new javax.swing.JLabel();
        tinNumberPayslipValue = new javax.swing.JLabel();
        empIDPayslipValue = new javax.swing.JLabel();
        empPositionValue = new javax.swing.JLabel();
        empStatusValue = new javax.swing.JLabel();
        payDateLabel = new javax.swing.JLabel();
        exitPayslip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setBackground(new java.awt.Color(240, 240, 240));

        ElectronicPayslip.setText("ELECTRONIC PAYSLIP OF:");
        ElectronicPayslip.setPreferredSize(new java.awt.Dimension(200, 26));
        employeeNameLabel.setPreferredSize(new java.awt.Dimension(300, 26));

        cutOff.setText("Payslip:");
        payDateLabel.setPreferredSize(new java.awt.Dimension(230, 23));

        viewPayslip.setText("View Payslip");
        viewPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPayslipActionPerformed(evt);
            }
        });

        downloadPayslip.setText("Download ");
        downloadPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadPayslipActionPerformed(evt);
            }
        });

        summary.setText("SUMMARY:");

        summary1.setText("Gross Income:");

        grossIncomeValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        benefits.setText("Benefits:");

        benefitsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        deductions.setText("Deductions:");

        deductionValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        deductions1.setText("Other Adjustments:");

        otherAdjustmentValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        netPay.setText("NET PAY:");

        netPayValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        payDetails.setText("PAY DETAILS:");

        salaryDetails.setText("Salary Details:");

        empIDPayslip.setText("Employee ID:");

        hoursWorked.setText("Basic Salary:");

        hourlyRate.setText("Hourly rate:");

        overtime.setText("Overtime:");
        lateLabel.setText("Late:");
        undertimeLabel.setText("Undertime:");

        hoursWorkedValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        hourlyRateValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        overtimeValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lateValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        undertimeValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        allowances.setText("Allownaces:");

        hoursWorked1.setText("Phone:");

        hoursWorked2.setText("Clothing:");

        hoursWorked3.setText("Rice:");

        deductionsBreakdown.setText("Deductions: ");

        pagibigDeductions.setText("Pag IBIG:");

        sssDeductions.setText("SSS Premium:");

        philhealthDeductions.setText("Philhealth:");

        phoneAllowanceValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clothingAllowanceValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        riceAllowanceValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sssDeductionsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        philhealthDeductionsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pagibigDeductionsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        withholdingTaxDeductions.setText("Withholding Tax:");

        withholdingTaxDeductionsValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        empPosition.setText("Employee Position: ");

        empStatus.setText("Employee Status:");

        pagibigNumberPayslip.setText("Pag IBIG:");

        sssNumberPayslip.setText("SSS:");

        philhealthNumberPayslip.setText("Philhealth:");

        tinNumberPayslip.setText("TIN:");

        employeeDetails.setText("EMPLOYEE DETAILS:");

        sssNumberPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        philhealthNumberPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pagibigNumberPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tinNumberPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        empIDPayslipValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        empPositionValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        empStatusValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        exitPayslip.setText("EXIT");
        exitPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitPayslipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ElectronicPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(netPay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(summary1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(benefits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deductions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deductions1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(benefitsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(grossIncomeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deductionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(otherAdjustmentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(netPayValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(summary, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salaryDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(hourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hourlyRateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(hoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hoursWorkedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(hoursWorked1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hoursWorked2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hoursWorked3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(undertimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(overtime, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sssDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(philhealthDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pagibigDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(undertimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(overtimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(clothingAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(phoneAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(riceAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(philhealthDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sssDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pagibigDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(withholdingTaxDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(withholdingTaxDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(allowances, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deductionsBreakdown, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(payDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cutOff, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cutoffDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(payDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sssNumberPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(philhealthNumberPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pagibigNumberPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tinNumberPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empIDPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sssNumberPayslipValue, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(philhealthNumberPayslipValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pagibigNumberPayslipValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tinNumberPayslipValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(empIDPayslipValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(empPositionValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(empStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(viewPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(downloadPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElectronicPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cutOff)
                    .addComponent(cutoffDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(payDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewPayslip)
                            .addComponent(downloadPayslip))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summary)
                    .addComponent(payDetails)
                    .addComponent(employeeDetails))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grossIncomeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryDetails)
                    .addComponent(summary1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(benefitsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(benefits))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deductionValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deductions)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hoursWorkedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoursWorked))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hourlyRateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hourlyRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(overtime)
                            .addComponent(overtimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lateLabel)
                            .addComponent(lateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(undertimeLabel)
                            .addComponent(undertimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empIDPayslip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empPosition)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empIDPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empPositionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empStatusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherAdjustmentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductions1)
                    .addComponent(allowances))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hoursWorked1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hoursWorked2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hoursWorked3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clothingAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(riceAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deductionsBreakdown))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sssNumberPayslip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(philhealthNumberPayslip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pagibigNumberPayslip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tinNumberPayslip)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(netPayValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(netPay))
                                .addGap(109, 109, 109))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sssDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(philhealthDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pagibigDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sssDeductions)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(philhealthDeductions)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pagibigDeductions)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(withholdingTaxDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(withholdingTaxDeductions))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sssNumberPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(philhealthNumberPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagibigNumberPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tinNumberPayslipValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitPayslip)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadPayslipActionPerformed
        String selectedCutoff = (String) cutoffDateCombo.getSelectedItem();
        LocalDate cutoffDateForName = cutoffDateOptions.get(selectedCutoff);
        String exportDateForName = (cutoffDateForName != null)
                ? cutoffDateForName.format(DateTimeFormatter.ofPattern("MM-dd-yyyy"))
                : "payslipdate";

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Save Payslip PDF");
        chooser.setSelectedFile(new File(exportDateForName + "_" + empNo + ".pdf"));
        int result = chooser.showSaveDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File selectedFile = chooser.getSelectedFile();
        String outputPath = selectedFile.getAbsolutePath().toLowerCase().endsWith(".pdf")
                ? selectedFile.getAbsolutePath()
                : selectedFile.getAbsolutePath() + ".pdf";

        JLabel exportPayslipText = new JLabel();
        String originalCutoffLabel = cutOff.getText();
        boolean originalComboVisible = cutoffDateCombo.isVisible();
        boolean originalViewVisible = viewPayslip.isVisible();
        boolean originalDownloadVisible = downloadPayslip.isVisible();
        boolean originalExitVisible = exitPayslip.isVisible();
        java.awt.Color originalBackground = getContentPane().getBackground();
        boolean exportTextAdded = false;

        try {
            LocalDate cutoffDate = cutoffDateOptions.get(selectedCutoff);
            String exportCutoffText = (cutoffDate != null)
                    ? cutoffDate.format(CSV_DATE_FORMAT)
                    : selectedCutoff;
            if (exportCutoffText == null || exportCutoffText.trim().isEmpty() || exportCutoffText.equals("Select cutoff date")) {
                JOptionPane.showMessageDialog(this, "Please select a valid payslip cutoff date first.");
                return;
            }
            cutOff.setText(originalCutoffLabel);

            cutoffDateCombo.setVisible(false);
            viewPayslip.setVisible(false);
            downloadPayslip.setVisible(false);
            exitPayslip.setVisible(false);
            getContentPane().setBackground(java.awt.Color.WHITE);

            exportPayslipText.setText(exportCutoffText);
            exportPayslipText.setFont(cutoffDateCombo.getFont());
            getContentPane().add(exportPayslipText);
            exportTextAdded = true;

            java.awt.Rectangle comboBounds = cutoffDateCombo.getBounds();
            exportPayslipText.setBounds(comboBounds.x, comboBounds.y, comboBounds.width, comboBounds.height);

            getContentPane().revalidate();
            getContentPane().repaint();

            BufferedImage image = new BufferedImage(
                    getContentPane().getWidth(),
                    getContentPane().getHeight(),
                    BufferedImage.TYPE_INT_RGB);
            java.awt.Graphics2D g2 = image.createGraphics();
            getContentPane().paint(g2);
            g2.dispose();

            Document document = new Document(PageSize.A4.rotate(), 20, 20, 20, 20);
            PdfWriter.getInstance(document, new FileOutputStream(outputPath));
            document.open();

            com.itextpdf.text.Image pdfImage = com.itextpdf.text.Image.getInstance(image, null);
            float pageWidth = document.getPageSize().getWidth() - document.leftMargin() - document.rightMargin();
            float pageHeight = document.getPageSize().getHeight() - document.topMargin() - document.bottomMargin();
            pdfImage.scaleToFit(pageWidth, pageHeight);
            pdfImage.setAlignment(Element.ALIGN_CENTER);
            document.add(pdfImage);

            document.close();
            JOptionPane.showMessageDialog(this, "Payslip saved to:\n" + outputPath);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to export payslip PDF:\n" + ex.getMessage(), "Export Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (exportTextAdded) {
                getContentPane().remove(exportPayslipText);
            }
            cutOff.setText(originalCutoffLabel);
            cutoffDateCombo.setVisible(originalComboVisible);
            viewPayslip.setVisible(originalViewVisible);
            downloadPayslip.setVisible(originalDownloadVisible);
            exitPayslip.setVisible(originalExitVisible);
            getContentPane().setBackground(originalBackground);
            getContentPane().revalidate();
            getContentPane().repaint();
        }
    }//GEN-LAST:event_downloadPayslipActionPerformed

    private void viewPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPayslipActionPerformed
    String selectedCutoff = (String) cutoffDateCombo.getSelectedItem();
    LocalDate cutoffDate = cutoffDateOptions.get(selectedCutoff);

    if (cutoffDate == null) {
        JOptionPane.showMessageDialog(this, "Please select a cutoff date from the list.");
        return;
    }

    LocalDate[] cutoffPeriod = salaryService.getCutoffPeriod(cutoffDate);
    LocalDate startDate = cutoffPeriod[0];
    LocalDate endDate = cutoffPeriod[1];

    EmployeeRepository empRepo = new EmployeeRepository();
    Employee emp = empRepo.findById(Integer.parseInt(this.empNo)).orElse(null);

    if (emp == null) {
        JOptionPane.showMessageDialog(this, "Employee not found!");
        return;
    }

    DateTimeFormatter displayFormat = DateTimeFormatter.ofPattern("MMM d");
    String periodLabel = "Cutoff Period: " + startDate.format(displayFormat) + " - " + endDate.format(displayFormat);
    payDateLabel.setText(periodLabel);

    PayslipData computation = salaryService.computePayslipData(emp, this.empNo, startDate, endDate);

    if (!computation.hasAttendance()) {
        JOptionPane.showMessageDialog(this, "No attendance records found for this cutoff. Net Pay is \u20B10.00.");
        updateSalaryDisplay(emp, computation);
        return;
    }

    fillEmployeeDetails(emp);
    updateSalaryDisplay(emp, computation);
}//GEN-LAST:event_viewPayslipActionPerformed
    private void loadCutoffDateOptions() {
        cutoffDateOptions.clear();

        if (this.empNo == null || this.empNo.trim().isEmpty()) {
            cutoffDateCombo.setModel(new DefaultComboBoxModel<>(new String[] {"Select cutoff date"}));
            return;
        }

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Select cutoff date");

        List<LocalDate> availableCutoffs = salaryService.getAvailableCutoffDates(this.empNo);
        for (LocalDate cutoffDate : availableCutoffs) {
            String label = cutoffDate.format(CSV_DATE_FORMAT);
            cutoffDateOptions.put(label, cutoffDate);
            model.addElement(label);
        }

        cutoffDateCombo.setModel(model);
    }

    private void exitPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPayslipActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitPayslipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payslip().setVisible(true);
            }
        });
    }
    
    private void updateSalaryDisplay(Employee emp, PayslipData computation) {
        hoursWorkedValue.setText(String.format("\u20B1%,.2f", computation.getSemiMonthlyBasicSalary()));
        overtimeValue.setText(String.format("%.2f", computation.getOvertimeAdjustment()));
        lateValue.setText(String.format("%.2f", computation.getLateAdjustment()));
        undertimeValue.setText(String.format("%.2f", computation.getUndertimeAdjustment()));

        setAttendanceAdjustmentVisibility(
                computation.getOvertimeAdjustment() != 0.0,
                computation.getLateAdjustment() != 0.0,
                computation.getUndertimeAdjustment() != 0.0);

        double totalAdjustments = computation.getOvertimeAdjustment()
                + computation.getLateAdjustment()
                + computation.getUndertimeAdjustment();
        otherAdjustmentValue.setText(String.format("\u20B1%,.2f", totalAdjustments));
        boolean hasOtherAdjustment = Math.abs(totalAdjustments) > 0.0001;
        deductions1.setVisible(hasOtherAdjustment);
        otherAdjustmentValue.setVisible(hasOtherAdjustment);

        grossIncomeValue.setText(String.format("\u20B1%,.2f", computation.getGross()));
        benefitsValue.setText(String.format("\u20B1%,.2f", computation.getAllowances()));
        sssDeductionsValue.setText(String.format("\u20B1%,.2f", computation.getSss()));
        philhealthDeductionsValue.setText(String.format("\u20B1%,.2f", computation.getPhilhealth()));
        pagibigDeductionsValue.setText(String.format("\u20B1%,.2f", computation.getPagibig()));
        withholdingTaxDeductionsValue.setText(String.format("\u20B1%,.2f", computation.getTax()));
        deductionValue.setText(String.format("\u20B1%,.2f", computation.getTotalDeductions()));
        netPayValue.setText(String.format("\u20B1%,.2f", computation.getNet()));
    }

    private void fillEmployeeDetails(Employee emp) {
        if (emp != null) {
            empIDPayslipValue.setText(String.valueOf(emp.getEmployeeNumber()));
            empPositionValue.setText(emp.getPosition());
            empStatusValue.setText(emp.getStatus());

            sssNumberPayslipValue.setText(emp.getSssNumber());
            tinNumberPayslipValue.setText(emp.getTinNumber());
            philhealthNumberPayslipValue.setText(emp.getPhilHealthNumber());
            pagibigNumberPayslipValue.setText(emp.getPagIbigNumber());

            riceAllowanceValue.setText(String.format("%.2f", emp.getRiceSubsidy() / 2));
            phoneAllowanceValue.setText(String.format("%.2f", emp.getPhoneAllowance() / 2));
            clothingAllowanceValue.setText(String.format("%.2f", emp.getClothingAllowance() / 2));

        }
    }

    private void setAttendanceAdjustmentVisibility(boolean hasOvertime, boolean hasLate, boolean hasUndertime) {
        overtime.setVisible(hasOvertime);
        overtimeValue.setVisible(hasOvertime);
        lateLabel.setVisible(hasLate);
        lateValue.setVisible(hasLate);
        undertimeLabel.setVisible(hasUndertime);
        undertimeValue.setVisible(hasUndertime);
    }

    private String formatAsHHmm(long totalMinutes) {
        long safeMinutes = Math.max(0L, totalMinutes);
        long hoursPart = safeMinutes / 60;
        long minutesPart = safeMinutes % 60;
        return String.format("%02d:%02d", hoursPart, minutesPart);
    }

    private void calculateFinalSalary(String empNo, String period) {
        try {
            payDateLabel.setText(period);
            empIDPayslipValue.setText(empNo);
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElectronicPayslip;
    private javax.swing.JLabel allowances;
    private javax.swing.JLabel benefits;
    private javax.swing.JLabel benefitsValue;
    private javax.swing.JLabel clothingAllowanceValue;
    private javax.swing.JLabel cutOff;
    private javax.swing.JComboBox<String> cutoffDateCombo;
    private javax.swing.JLabel deductionValue;
    private javax.swing.JLabel deductions;
    private javax.swing.JLabel deductions1;
    private javax.swing.JLabel deductionsBreakdown;
    private javax.swing.JButton downloadPayslip;
    private javax.swing.JLabel empIDPayslip;
    private javax.swing.JLabel empIDPayslipValue;
    private javax.swing.JLabel empPosition;
    private javax.swing.JLabel empPositionValue;
    private javax.swing.JLabel empStatus;
    private javax.swing.JLabel empStatusValue;
    private javax.swing.JLabel employeeDetails;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JButton exitPayslip;
    private javax.swing.JLabel grossIncomeValue;
    private javax.swing.JLabel hourlyRate;
    private javax.swing.JLabel hourlyRateValue;
    private javax.swing.JLabel hoursWorked;
    private javax.swing.JLabel hoursWorked1;
    private javax.swing.JLabel hoursWorked2;
    private javax.swing.JLabel hoursWorked3;
    private javax.swing.JLabel hoursWorkedValue;
    private javax.swing.JLabel lateLabel;
    private javax.swing.JLabel lateValue;
    private javax.swing.JLabel netPay;
    private javax.swing.JLabel netPayValue;
    private javax.swing.JLabel otherAdjustmentValue;
    private javax.swing.JLabel overtime;
    private javax.swing.JLabel overtimeValue;
    private javax.swing.JLabel pagibigDeductions;
    private javax.swing.JLabel pagibigDeductionsValue;
    private javax.swing.JLabel pagibigNumberPayslip;
    private javax.swing.JLabel pagibigNumberPayslipValue;
    private javax.swing.JLabel payDateLabel;
    private javax.swing.JLabel payDetails;
    private javax.swing.JLabel philhealthDeductions;
    private javax.swing.JLabel philhealthDeductionsValue;
    private javax.swing.JLabel philhealthNumberPayslip;
    private javax.swing.JLabel philhealthNumberPayslipValue;
    private javax.swing.JLabel phoneAllowanceValue;
    private javax.swing.JLabel riceAllowanceValue;
    private javax.swing.JLabel salaryDetails;
    private javax.swing.JLabel sssDeductions;
    private javax.swing.JLabel sssDeductionsValue;
    private javax.swing.JLabel sssNumberPayslip;
    private javax.swing.JLabel sssNumberPayslipValue;
    private javax.swing.JLabel summary;
    private javax.swing.JLabel summary1;
    private javax.swing.JLabel tinNumberPayslip;
    private javax.swing.JLabel tinNumberPayslipValue;
    private javax.swing.JLabel undertimeLabel;
    private javax.swing.JLabel undertimeValue;
    private javax.swing.JButton viewPayslip;
    private javax.swing.JLabel withholdingTaxDeductions;
    private javax.swing.JLabel withholdingTaxDeductionsValue;
    // End of variables declaration//GEN-END:variables
}


