/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author singh
 */

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;


public class LoginScreen1 extends javax.swing.JFrame {
    
    private final String DEFAULT_USERNAME = "admin";
    private final String DEFAULT_PASSWORD = "12345";
    private int failedAttempts = 0;
    private long blockUntilTime = 0;



    /**
     * Creates new form LoginScreen1
     */
    public LoginScreen1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textLogo = new javax.swing.JLabel();
        loginLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelLogin2 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 49, 113));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textLogo.setFont(new java.awt.Font("Kinetika Bold", 0, 55)); // NOI18N
        textLogo.setForeground(new java.awt.Color(255, 255, 255));
        textLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLogo.setText("MotorPH");
        jPanel1.add(textLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 492, -1, -1));

        loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginLogo.png"))); // NOI18N
        jPanel1.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 137, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 602));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 282, 201, -1));

        jLabelUsername.setText("Username:");
        jPanel2.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 285, 100, -1));

        jLabelPassword.setText("Password:");
        jPanel2.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 327, 100, -1));

        jButtonLogin.setBackground(new java.awt.Color(14, 49, 113));
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, 32));

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 324, 201, -1));

        jLabelLogin2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelLogin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin2.setText("Employee Login");
        jPanel2.add(jLabelLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 148, -1, -1));

        jButtonReset.setBackground(new java.awt.Color(14, 49, 113));
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Reset Password");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 120, 32));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("CP2 H1102 SY24-25 Team Petix - C.Oreta, S.Singh, R.Sisles, J.Singh, D.Sumatra");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 300, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 0, 590, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
    long currentTime = System.currentTimeMillis();

    // ⏳ Check if user is currently blocked
    if (currentTime < blockUntilTime) {
        long secondsRemaining = (blockUntilTime - currentTime) / 1000;
        JOptionPane.showMessageDialog(this,
            "Too many incorrect attempts.\nYour account is temporarily blocked for " + secondsRemaining + " seconds.\n" +
            "Please wait or reset your password.",
            "Login Blocked",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    String username = jTextFieldUsername.getText().trim();
    String password = jPasswordField.getText().trim();

    User user = UserDatabase.authenticate(username, password);

    if (user != null) {
        // 🔐 Successful login
        User.setLoggedInUser(user);
        failedAttempts = 0;
        blockUntilTime = 0;

        JOptionPane.showMessageDialog(this, "Welcome, " + user.getFirstName() + "!");

        MainMenu main = new MainMenu(user);
        main.setVisible(true);
        main.setLocationRelativeTo(null);

        // Optional role-based actions (kept intact)
        switch (user.getRole().toUpperCase()) {
            case "EMPLOYEE":
                // new Attendance(user.getEmployeeId()).setVisible(true);
                break;
            case "HR":
                // optional: HR interface
                break;
            case "SUPPORT":
                // optional: Support interface
                break;
            case "ADMIN":
                // optional: Admin interface
                break;
        }

        this.dispose();
    } else {
        // ❌ Incorrect login
        failedAttempts++;

        if (failedAttempts >= 3) {
            blockUntilTime = System.currentTimeMillis() + (5 * 60 * 1000); // 5-minute lockout
            JOptionPane.showMessageDialog(this,
                "Invalid login 3 times.\nAccount is locked for 5 minutes.\n" +
                "Consider resetting your password.",
                "Account Temporarily Blocked",
                JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "Invalid username or password.\nAttempt " + failedAttempts + " of 3.",
                "Login Failed",
                JOptionPane.WARNING_MESSAGE);
        }

        jTextFieldUsername.setText("");
        jPasswordField.setText("");
    }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
    String empId = JOptionPane.showInputDialog(this, "Enter your Employee ID:");
    if (empId == null || empId.trim().isEmpty()) return;

    String question = UserDatabase.getSecurityQuestion(empId.trim());
    if (question == null) {
        JOptionPane.showMessageDialog(this, "Employee ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String answer = JOptionPane.showInputDialog(this, question);
    if (answer == null || answer.trim().isEmpty()) return;

    boolean isCorrect = UserDatabase.verifySecurityAnswer(empId.trim(), answer.trim());
    if (!isCorrect) {
        JOptionPane.showMessageDialog(this, "Incorrect answer. Please try again.", "Security Check Failed", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String newPassword = null;
    boolean validPassword = false;

    // 🔁 Repeat until user enters a valid password or cancels
    while (!validPassword) {
        JPasswordField passwordField = new JPasswordField();
        passwordField.setEchoChar('*');

        int confirm = JOptionPane.showConfirmDialog(this, passwordField, "Enter your new password:", JOptionPane.OK_CANCEL_OPTION);

        if (confirm != JOptionPane.OK_OPTION) {
            JOptionPane.showMessageDialog(this, "Password reset canceled.");
            return;
        }

        newPassword = new String(passwordField.getPassword()).trim();

        boolean isAlphanumeric = newPassword.matches("^[a-zA-Z0-9]+$");
        boolean hasCapital = newPassword.matches(".*[A-Z].*");
        boolean hasNumber = newPassword.matches(".*\\d.*");

        if (newPassword.isEmpty() || !isAlphanumeric || !hasCapital || !hasNumber) {
            JOptionPane.showMessageDialog(this,
                "Password must meet the following requirements:\n" +
                "- Only letters and numbers (no symbols)\n" +
                "- At least one uppercase letter\n" +
                "- At least one number",
                "Invalid Password Format",
                JOptionPane.ERROR_MESSAGE);
        } else {
            validPassword = true;
        }
    }

    boolean updated = UserDatabase.updatePassword(empId.trim(), newPassword);
    if (updated) {
        JOptionPane.showMessageDialog(this, "Password reset successfully.");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to update password.", "Update Failed", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogin2;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JLabel textLogo;
    // End of variables declaration//GEN-END:variables
}
